# Generated by Django 4.2.6 on 2023-12-02 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_category_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_available',
            field=models.BooleanField(default=False),
        ),
    ]
